# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('bio', models.CharField(max_length=300)),
                ('jabber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('skype', models.CharField(max_length=50)),
                ('other', models.CharField(max_length=300)),
            ],
        ),
    ]
