# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='date',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
