# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20160108_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('uri', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(max_length=3)),
                ('content_length', models.IntegerField(max_length=10)),
            ],
        ),
    ]
