# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_httprequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httprequests',
            name='content_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='httprequests',
            name='status_code',
            field=models.IntegerField(),
        ),
    ]
