# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20160109_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='httprequests',
            options={'ordering': ['date_time']},
        ),
        migrations.RenameField(
            model_name='httprequests',
            old_name='protocol',
            new_name='server_protocol',
        ),
    ]
