# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20160109_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('request_method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=10)),
                ('server_protocol', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.DeleteModel(
            name='HttpRequests',
        ),
    ]
