# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20160110_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('uri', models.CharField(max_length=100)),
                ('server_protocol', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('content_length', models.IntegerField()),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
