# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20160110_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='content_length',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='request',
            name='status_code',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
