# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20160110_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['date_time']},
        ),
        migrations.RenameField(
            model_name='request',
            old_name='time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='path',
            new_name='uri',
        ),
    ]
